name: SaveImagesTwitterToS3 CICD

on:
  push:
    branches:
        - main
  pull_request:
jobs:
  aws_cdk:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.x'
      
      - name: Setup CDK
        run: |
          npm install -g aws-cdk
          cdk --version

      - name: Setup dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Build
        run: sh deploy.sh

      - name: Unit tests
        if: contains(github.event_name, 'pull_request')
        run: python -m pytest
          
      - name: CDK Diff Check
        if: contains(github.event_name, 'pull_request')
        run: cdk diff
        env:
          AWS_DEFAULT_REGION: 'ap-northeast-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: CDK Deploy
        if: contains(github.event_name, 'push')
        run: cdk deploy
        env:
          AWS_DEFAULT_REGION: 'ap-northeast-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}